# Generated by Django 5.0.7 on 2024-07-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PlantomioControllApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Devices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DeviceID", models.CharField(max_length=200)),
                ("DeviceName", models.CharField(max_length=200)),
                ("DeviceType", models.CharField(max_length=200)),
                ("DeviceAddress", models.CharField(max_length=200)),
                ("DeviceGroup", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="DropdownOption",
        ),
    ]
