# Generated by Django 5.0.7 on 2024-08-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PlantomioControllApp", "0002_devices_delete_dropdownoption"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devices",
            name="DeviceAddress",
        ),
        migrations.RemoveField(
            model_name="devices",
            name="DeviceGroup",
        ),
        migrations.RemoveField(
            model_name="devices",
            name="DeviceID",
        ),
        migrations.RemoveField(
            model_name="devices",
            name="DeviceName",
        ),
        migrations.RemoveField(
            model_name="devices",
            name="DeviceType",
        ),
        migrations.AddField(
            model_name="devices",
            name="device_address",
            field=models.CharField(default="none", max_length=100),
        ),
        migrations.AddField(
            model_name="devices",
            name="device_group",
            field=models.CharField(default="none", max_length=100),
        ),
        migrations.AddField(
            model_name="devices",
            name="device_id",
            field=models.CharField(default="none", max_length=100),
        ),
        migrations.AddField(
            model_name="devices",
            name="device_name",
            field=models.CharField(default="none", max_length=100),
        ),
    ]
