# Generated by Django 5.0.7 on 2024-08-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PlantomioControllApp", "0003_remove_devices_deviceaddress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devices",
            name="device_type",
            field=models.CharField(default="none", max_length=100),
        ),
    ]
