# Generated by Django 5.0.7 on 2024-08-02 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PlantomioControllApp", "0004_devices_device_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PlantomioControllApp.devices",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Groups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_number", models.CharField(default="none", max_length=100)),
                ("group_name", models.CharField(default="none", max_length=100)),
                ("group_type", models.CharField(default="none", max_length=100)),
                (
                    "group_devices",
                    models.ManyToManyField(
                        through="PlantomioControllApp.GroupDevice",
                        to="PlantomioControllApp.devices",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="groupdevice",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="PlantomioControllApp.groups",
            ),
        ),
    ]
