# Generated by Django 5.0.7 on 2024-08-02 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("PlantomioControllApp", "0006_remove_devices_device_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GroupDevice",
            new_name="GroupDevices",
        ),
    ]
