# Generated by Django 5.0.7 on 2024-08-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PlantomioControllApp", "0007_rename_groupdevice_groupdevices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupdevices",
            name="device",
        ),
        migrations.RemoveField(
            model_name="groupdevices",
            name="group",
        ),
        migrations.RemoveField(
            model_name="groups",
            name="group_devices",
        ),
        migrations.AddField(
            model_name="groupdevices",
            name="devices",
            field=models.ManyToManyField(
                related_name="group_devices", to="PlantomioControllApp.devices"
            ),
        ),
        migrations.AddField(
            model_name="groupdevices",
            name="group_name",
            field=models.CharField(default="none", max_length=100, unique=True),
        ),
    ]
