# Generated by Django 5.0.7 on 2024-08-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PlantomioControllApp", "0009_alter_groupdevices_group_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupdevices",
            name="group_name",
            field=models.CharField(default="none", max_length=100, unique=True),
        ),
    ]
