# Generated by Django 5.0.7 on 2024-08-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PlantomioControllApp", "0010_alter_groupdevices_group_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="devices",
            name="devive_id",
            field=models.CharField(default="none", max_length=100),
        ),
    ]
