# Generated by Django 5.0.7 on 2024-08-02 18:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("PlantomioControllApp", "0011_devices_devive_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="devices",
            old_name="devive_id",
            new_name="device_id",
        ),
    ]
