# Generated by Django 5.0.7 on 2024-08-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PlantomioControllApp", "0012_rename_devive_id_devices_device_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_number",
                    models.CharField(default="none", max_length=100, unique=True),
                ),
                ("group_name", models.CharField(default="none", max_length=100)),
                (
                    "devices",
                    models.ManyToManyField(
                        related_name="group_devices", to="PlantomioControllApp.devices"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="GroupDevices",
        ),
    ]
