# Generated by Django 5.0.7 on 2024-08-02 19:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("PlantomioControllApp", "0013_plantgroups_delete_groupdevices"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Groups",
        ),
    ]
