# Generated by Django 5.0.7 on 2024-08-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PlantomioControllApp", "0014_delete_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantgroups",
            name="devices",
            field=models.ManyToManyField(to="PlantomioControllApp.devices"),
        ),
        migrations.CreateModel(
            name="ClimateGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_number",
                    models.CharField(default="none", max_length=100, unique=True),
                ),
                ("group_name", models.CharField(default="none", max_length=100)),
                ("devices", models.ManyToManyField(to="PlantomioControllApp.devices")),
            ],
        ),
        migrations.CreateModel(
            name="TankGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_number",
                    models.CharField(default="none", max_length=100, unique=True),
                ),
                ("group_name", models.CharField(default="none", max_length=100)),
                ("devices", models.ManyToManyField(to="PlantomioControllApp.devices")),
            ],
        ),
    ]
