# Generated by Django 5.0.7 on 2024-08-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PlantomioControllApp", "0016_rename_plantgroups_climategroup_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="climategroup",
            old_name="group_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="climategroup",
            old_name="group_number",
            new_name="number",
        ),
        migrations.RenameField(
            model_name="device",
            old_name="device_address",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="device",
            old_name="device_group",
            new_name="groupNumber",
        ),
        migrations.RenameField(
            model_name="device",
            old_name="device_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="device",
            old_name="device_type",
            new_name="role",
        ),
        migrations.RenameField(
            model_name="plantgroup",
            old_name="group_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="plantgroup",
            old_name="group_number",
            new_name="number",
        ),
        migrations.RenameField(
            model_name="tankgroup",
            old_name="group_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="tankgroup",
            old_name="group_number",
            new_name="number",
        ),
        migrations.RemoveField(
            model_name="device",
            name="device_id",
        ),
        migrations.AddField(
            model_name="device",
            name="groupType",
            field=models.CharField(default="none", max_length=100),
        ),
        migrations.AddField(
            model_name="device",
            name="type",
            field=models.CharField(default="none", max_length=100),
        ),
        migrations.AlterField(
            model_name="device",
            name="id",
            field=models.CharField(
                default="none", max_length=100, primary_key=True, serialize=False
            ),
        ),
    ]
