# Generated by Django 5.0.7 on 2024-08-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PlantomioControllApp", "0017_rename_group_name_climategroup_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantgroup",
            name="activClimateGroup",
            field=models.CharField(default="none", max_length=100),
        ),
        migrations.AddField(
            model_name="plantgroup",
            name="activPlantPlan",
            field=models.CharField(default="none", max_length=100),
        ),
        migrations.AddField(
            model_name="plantgroup",
            name="activTankGroup",
            field=models.CharField(default="none", max_length=100),
        ),
    ]
