# Generated by Django 5.0.7 on 2024-08-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PlantomioControllApp", "0018_plantgroup_activclimategroup_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantPlan",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="none",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plant", models.CharField(default="none", max_length=100)),
                ("name", models.CharField(default="none", max_length=100, unique=True)),
                ("weeks", models.CharField(default="none", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PlanValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planId", models.CharField(default="none", max_length=100)),
                ("week", models.CharField(default="none", max_length=100)),
                ("phase", models.CharField(default="none", max_length=100)),
                ("moistureTarget", models.CharField(default="none", max_length=100)),
                ("moistureMinimum", models.CharField(default="none", max_length=100)),
                ("moistureMaximum", models.CharField(default="none", max_length=100)),
                ("brightnessTarget", models.CharField(default="none", max_length=100)),
                ("brightnessMinimum", models.CharField(default="none", max_length=100)),
                ("brightnessMaximum", models.CharField(default="none", max_length=100)),
                ("lighthoursTarget", models.CharField(default="none", max_length=100)),
                ("lighthoursMinimum", models.CharField(default="none", max_length=100)),
                ("lighthoursMaximum", models.CharField(default="none", max_length=100)),
                ("ecTarget", models.CharField(default="none", max_length=100)),
                ("ecMinimum", models.CharField(default="none", max_length=100)),
                ("ecMaximum", models.CharField(default="none", max_length=100)),
                ("phTarget", models.CharField(default="none", max_length=100)),
                ("phMinimum", models.CharField(default="none", max_length=100)),
                ("phMaximum", models.CharField(default="none", max_length=100)),
                ("temperatureTarget", models.CharField(default="none", max_length=100)),
                (
                    "temperatureMinimum",
                    models.CharField(default="none", max_length=100),
                ),
                (
                    "temperatureMaximum",
                    models.CharField(default="none", max_length=100),
                ),
                ("humidityTarget", models.CharField(default="none", max_length=100)),
                ("humidityMinimum", models.CharField(default="none", max_length=100)),
                ("humidityMaximum", models.CharField(default="none", max_length=100)),
                ("information", models.CharField(default="none", max_length=100)),
            ],
        ),
    ]
