# Generated by Django 5.0.7 on 2024-08-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PlantomioControllApp", "0019_plantplan_planvalue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planvalue",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
