# Generated by Django 5.0.7 on 2024-08-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PlantomioControllApp", "0020_alter_planvalue_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantplan",
            name="values",
            field=models.ManyToManyField(to="PlantomioControllApp.planvalue"),
        ),
    ]
