# Generated by Django 5.0.7 on 2024-08-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PlantomioControllApp", "0021_plantplan_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantplan",
            name="name",
            field=models.CharField(default="none", max_length=100),
        ),
    ]
