# Generated by Django 5.0.7 on 2024-08-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PlantomioControllApp", "0022_alter_plantplan_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantgroup",
            name="startDate",
            field=models.DateField(default="none"),
        ),
    ]
