# Generated by Django 5.0.7 on 2024-08-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PlantomioControllApp", "0023_plantgroup_startdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantgroup",
            name="startDate",
            field=models.DateField(default="2021-01-01"),
        ),
    ]
