# Generated by Django 5.0.7 on 2024-08-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PlantomioControllApp", "0024_alter_plantgroup_startdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantgroup",
            name="startDate",
            field=models.DateField(default="none", max_length=100),
        ),
    ]
