# Generated by Django 5.0.7 on 2024-08-05 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("PlantomioControllApp", "0025_alter_plantgroup_startdate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantgroup",
            name="startDate",
        ),
    ]
